### ISSUE TITLE
배포 자동화 파이프라인 구축

### ISSUE THREAD

**Issue by YehyeokBang** [ProjectBARO/BARO-Server#1]
Cloud Build 트리거를 추가
- main 브랜치에 push 될 때 실행
- Dockerfile을 통해 이미지를 빌드
- 이미지를 Artifact Resistry에 저장
- Cloud Run 자동 배포

## 결과
![Image](https://github.com/ProjectBARO/BARO-Server/assets/107793780/538ba566-4b30-4c10-a703-dd56b8f88571)

**Comment by YehyeokBang** [comment]
완료

**Comment by cucumber99** [comment]
Good

**Comment by YehyeokBang** [comment]
Thank you
