### ISSUE TITLE
사용자 모델에 들어갈 필드 토론

### ISSUE THREAD

**Issue by YehyeokBang** [ProjectBARO/BARO-Server#6]
```go
type User struct {
	ID       uint   `json:"id" gorm:"primary_key"`
	Name     string `json:"name"`
	Nickname string `json:"nickname"`
	Email    string `json:"email" gorm:"unique"`
	Age      int    `json:"age"`
	Gender   string `json:"gender"`
	Deleted  gorm.DeletedAt
}
```

## 현재 필드
- `ID` : 데이터베이스의 Primary Key
- `Name` : 사용자의 이름, 구글 측에서 받아옴
- `Nickname` : 초기에는 사용자의 이름으로 구성됨, 변경할 수 있음 API 구성 중
- `Email` : 구글 로그인 시 사용하는 사용자의 이메일, 변경할 수 없으며 유일함(unique)
- `Age` : 사용자의 나이, 사용자가 직접 입력해야함
- `Gender` : 사용자의 성별, 나이와 동일함
- `Deleted` : Soft Delete를 위한 필드, 크게 신경쓰지 않아도 됨 (관련 이슈 #5)

## 주제
필드에 대한 추가, 수정, 삭제와 관련된 의견을 부탁합니다.
ex) 사용자 프로필 이미지 URL 추가하면 어떨까요? 등

**Comment by shinheekim** [comment]
저는 현재로썬 더 추가할 필드는 없을 것 같습니다. 프로필 이미지를 추가할지에 대한 논의는 필요할 거 같아요!

**Comment by YehyeokBang** [comment]
가입 날짜 필드도 있으면 좋을 것 같아요. 추가로 생일도 있으면 앱 내에서 할 수 있는 서비스가 늘어나지 않을까? 라는 생각이 들기도 하네요.

**Comment by shinheekim** [comment]
사용자가 앉은 자세일 때 어느 부분이 불편한지에 대해 받으면 좋을 거 같아요. 이 정보는 회원가입 시에 받는 것이 아니라 추후 이용하던 중에 사용자 맞춤 정보 입력 팝업을 띄워 정보를 받아봐도 좋을 것 같습니다.
