### ISSUE TITLE
보고서 모델 추가, 필드 토론

### ISSUE THREAD

**Issue by YehyeokBang** [ProjectBARO/BARO-Server#8]
## 요청사항
- @Ryuchanghoon  무슨 결과 값을 줄 수 있는지 필드와 설명을 부탁드려요.
예시) 형식은 쉽게 이해할 수 있게 JSON 형식과 유사하게 설명함
```
{
    "필드" : "타입", "설명",
    "score" : 실수형, "거북목인 경우 100점",
    "nX" : "실수형", "추출한 목의 x좌표",
}
```
위 형태는 예시이며 이를 참고하여 결과값 필드를 알려주세요!

**Comment by Ryuchanghoon** [comment]
![Image](https://github.com/ProjectBARO/BARO-Server/assets/107829554/6f42e255-19b1-4adb-9a78-b1609d6e40fb)

</br>


{

"왼쪽 귀" : "string", "x축 좌표, y축 좌표"

"왼쪽 어깨" : "float", "x축 좌표, y축 좌표"

"거북목 상태" : "정상", or "비정상"

}



</br>
</br>

현재까지는 코드상에서 이런식으로 구현을 했습니다.
서버 파트에 값을 넘겨줄 때는 "거북목 상태"에 대한 결과값을 이 과정에서 바로 넘겨줄지 말지는 고민을 해봐야겠지만
코드상에서는 이렇게 출력을 뽑아냈습니다.
각 부위별 출력은 더 추가할 계획입니다.

**Comment by YehyeokBang** [comment]
현재 서버 측에서 예상 중인 필드

```
- 보고서 ID (PK)
- 사용자 ID (FK)
- 측정 날짜
- 측정 시간
- 알림 횟수
- 자세 점수 ex) 5초마다 0 or 1 값을 받았다면, 값을 합산하고 100점에 맞게 변환
- 귀와 어깨 중심의 평균적인 좌표 값 or 둘의 차의 평균 등
```
</br>

이외에 추가적인 필드를 넣을 수 있을까요? (가능 여부 또는 추가를 원하는 필드)

**Comment by YehyeokBang** [comment]
```
- ID 데이터베이스 기본키
- UserID 사용자 ID
- Predict 분석 결과
- CreatedAt 분석 날짜
```

앱으로 부터 받는 측정 시간, 알림 횟수는 아직 구현하지 않았습니다.

현재 테스트 중인 모델 서버의 결과 값은 아래와 같기 때문에 문자열로 저장합니다.
```
[1, 1, 1, 0, 1, 1, 1, 1, 1, 1]
```

모델 변경 및 서버 배포가 완료되면 말씀해주세요 @Ryuchanghoon 
관련된 PR #17

**Comment by Ryuchanghoon** [comment]
일단 모델 보강이 끝난 다음, 

100분위 변환 및 평균 좌표값 등등, 
추가적인 함수 구현은 api 배포 할 때 함께 작업할 계획입니다.

작업 하나 끝날 때 마다 바로바로 말씀 드리겠습니다.
